# Generated by Django 4.0.4 on 2022-06-09 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGenreM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companygenre', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': '業者ジャンル',
            },
        ),
        migrations.CreateModel(
            name='SpotCompanyM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, '2文字以上としてください')])),
                ('genre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Spots.companygenrem')),
            ],
            options={
                'verbose_name_plural': 'Spot & Company',
            },
        ),
        migrations.CreateModel(
            name='spotcompanyDetailM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみ入力可')], verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみ入力可')], verbose_name='FAX番号')),
                ('add', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='住所')),
                ('man', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='spotcompanyD', to='Spots.spotcompanym')),
            ],
            options={
                'verbose_name_plural': 'SpotCompany詳細',
            },
        ),
    ]
