# Generated by Django 4.0.4 on 2022-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0012_alter_soenmemberdetailm_age_alter_soenmemberm_name'),
        ('Spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygenrem',
            options={'verbose_name_plural': '会社ジャンル'},
        ),
        migrations.AddField(
            model_name='spotcompanydetailm',
            name='vehicle',
            field=models.ManyToManyField(blank=True, null=True, to='Soen.vehiclem'),
        ),
        migrations.AlterField(
            model_name='spotcompanydetailm',
            name='add',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所'),
        ),
    ]
