# Generated by Django 4.0.4 on 2022-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0016_specialeducationm_image1'),
        ('Spots', '0002_alter_companygenrem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotcompanydetailm',
            name='vehicle',
            field=models.ManyToManyField(blank=True, default='', null=True, to='Soen.vehiclem'),
        ),
    ]
