# Generated by Django 4.0.4 on 2022-06-21 02:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0018_alter_licencem_man_alter_skillm_man_and_more'),
        ('Spots', '0003_alter_spotcompanydetailm_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, '2文字以上としてください')])),
                ('add', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', '英数字のみ入力可')], verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', '英数字のみ入力可')], verbose_name='FAX番号')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='SpotM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, '2文字以上としてください')])),
                ('add', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', '英数字のみ入力可')], verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', '英数字のみ入力可')], verbose_name='FAX番号')),
                ('forthCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forthcompany', to='Spots.companym')),
                ('generalCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spots.companym')),
            ],
            options={
                'verbose_name_plural': 'Aspot',
            },
        ),
        migrations.RemoveField(
            model_name='spotcompanym',
            name='genre',
        ),
        migrations.AlterModelOptions(
            name='companygenrem',
            options={'verbose_name_plural': 'spotCompanyジャンル'},
        ),
        migrations.DeleteModel(
            name='spotcompanyDetailM',
        ),
        migrations.DeleteModel(
            name='SpotCompanyM',
        ),
        migrations.AddField(
            model_name='spotm',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spots.companygenrem'),
        ),
        migrations.AddField(
            model_name='spotm',
            name='primaryCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primarycompany', to='Spots.companym'),
        ),
        migrations.AddField(
            model_name='spotm',
            name='primaryCompanyMember',
            field=models.ManyToManyField(to='Soen.soenmemberm'),
        ),
        migrations.AddField(
            model_name='spotm',
            name='secondaryCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondarycompany', to='Spots.companym'),
        ),
        migrations.AddField(
            model_name='spotm',
            name='thirdCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdcompany', to='Spots.companym'),
        ),
        migrations.AddField(
            model_name='companym',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spots.companygenrem'),
        ),
        migrations.AddField(
            model_name='companym',
            name='vehicle',
            field=models.ManyToManyField(blank=True, default='', null=True, to='Soen.vehiclem'),
        ),
    ]
