# Generated by Django 4.0.4 on 2022-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spots', '0004_companym_spotm_remove_spotcompanym_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotGenreM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotgenre', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'spotCompanyジャンル',
            },
        ),
    ]
