# Generated by Django 4.0.4 on 2022-06-22 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spots', '0005_spotgenrem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygenrem',
            options={'verbose_name_plural': 'Companyジャンル'},
        ),
        migrations.AlterModelOptions(
            name='spotgenrem',
            options={'verbose_name_plural': 'spotジャンル'},
        ),
        migrations.AlterField(
            model_name='spotm',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spots.spotgenrem'),
        ),
        migrations.CreateModel(
            name='SpotDetailM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationmanager', models.CharField(max_length=30)),
                ('spotdetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotdetail', to='Spots.spotm')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetailM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=30)),
                ('companydetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companyDetail', to='Spots.companym')),
            ],
        ),
    ]
