# Generated by Django 4.0.4 on 2022-06-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spots', '0006_alter_companygenrem_options_alter_spotgenrem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetailm',
            options={'verbose_name_plural': '各 会社詳細'},
        ),
        migrations.AlterModelOptions(
            name='companym',
            options={'verbose_name_plural': '各 会社'},
        ),
        migrations.AlterModelOptions(
            name='spotdetailm',
            options={'verbose_name_plural': '工事現場詳細'},
        ),
        migrations.AlterModelOptions(
            name='spotm',
            options={'verbose_name_plural': '工事現場'},
        ),
        migrations.RenameField(
            model_name='spotm',
            old_name='name',
            new_name='spotname',
        ),
        migrations.AlterField(
            model_name='spotdetailm',
            name='spotdetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotDetail', to='Spots.spotm'),
        ),
    ]
