# Generated by Django 4.0.4 on 2022-05-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': '大枠',
            },
        ),
        migrations.CreateModel(
            name='SoenMemberM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('genre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Soen.genrem')),
            ],
            options={
                'verbose_name_plural': 'soen関係者',
            },
        ),
        migrations.CreateModel(
            name='VehicleM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.CharField(default='佐世保\u3000あ\u300050\u300050-50', max_length=20, verbose_name='車両番号')),
                ('firstUse', models.DateField(blank=True, null=True, verbose_name='使用期間開始')),
                ('finishUse', models.DateField(blank=True, null=True, verbose_name='使用期間終了')),
                ('vehicleModel', models.CharField(blank=True, max_length=20, null=True, verbose_name='車検証_型式')),
                ('firstInspection', models.DateField(blank=True, null=True, verbose_name='車検証_車検期間開始')),
                ('finishInspection', models.DateField(blank=True, null=True, verbose_name='車検証_車検期間終了')),
                ('file1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link1車検証')),
                ('liabilityComp', models.CharField(blank=True, max_length=20, null=True, verbose_name='自賠責_保険会社')),
                ('liability_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='自賠責_証券番号')),
                ('firstliability', models.DateField(blank=True, null=True, verbose_name='自賠責_保険期間開始')),
                ('finishliability', models.DateField(blank=True, null=True, verbose_name='自賠責_保険期間終了')),
                ('file2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link2自賠責')),
                ('voluntaryInsureComp', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_保険会社')),
                ('voluntaryInsureNum', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_証券番号')),
                ('firstVoluntary', models.DateField(blank=True, null=True, verbose_name='任意保険_保険期間開始')),
                ('finishVoluntary', models.DateField(blank=True, null=True, verbose_name='任意保険_保険期間終了')),
                ('voluntary_object', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_対物_千円')),
                ('voluntary_human', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_対人_千円')),
                ('voluntary_passenger', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_搭乗者_千円')),
                ('file3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link3任意保険')),
                ('drive_departure', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_出発地')),
                ('drive_waypoint1', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_経由1')),
                ('drive_waypoint2', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_経由2')),
                ('drive_arrival', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_到着地')),
                ('man', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Soen.soenmemberm')),
            ],
            options={
                'verbose_name_plural': '車両',
            },
        ),
        migrations.CreateModel(
            name='SpecialEducationM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialeducation', models.CharField(blank=True, choices=[('0', '-'), ('1', '研削といし取替・試運転'), ('2', 'アーク溶接作業'), ('3', 'フォークリフト運転業務'), ('4', '高所作業車の運転'), ('5', '巻き上げ機の運転'), ('6', 'クレーンの運転'), ('7', '移動式クレーンの運転'), ('8', '玉掛け業務'), ('9', '職長教育'), ('10', '職長教育（追教育）'), ('11', '安全衛生責任者'), ('12', '足場組立等作業従事者特別教育'), ('13', '有機溶剤取扱い業務'), ('14', '特別教育14'), ('15', '特別教育15')], max_length=30, null=True, verbose_name='特別教育')),
                ('man', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Soen.soenmemberm')),
            ],
            options={
                'verbose_name_plural': '特別教育',
            },
        ),
    ]
