# Generated by Django 4.0.4 on 2022-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialeducationm',
            name='specialeducation',
            field=models.CharField(blank=True, choices=[('0', '-'), ('研と', '研削といし取替・試運転'), ('ｱｰｸ', 'アーク溶接作業'), ('ﾌｫｰｸ', 'フォークリフト運転業務'), ('高作車', '高所作業車の運転'), ('巻機', '巻き上げ機の運転'), ('ｸﾚｰﾝ', 'クレーンの運転'), ('移ｸﾚｰﾝ', '移動式クレーンの運転'), ('玉掛', '玉掛け業務'), ('職', '職長教育'), ('職(追)', '職長教育（追教育）'), ('安衛責', '安全衛生責任者'), ('足場', '足場組立等作業従事者特別教育'), ('有溶剤', '有機溶剤取扱い業務'), ('特14', '特別教育14'), ('特15', '特別教育15')], max_length=30, null=True, verbose_name='特別教育'),
        ),
    ]
