# Generated by Django 4.0.4 on 2022-05-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0002_alter_specialeducationm_specialeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='soenmemberDetailM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('add', models.CharField(blank=True, default='長崎県佐世保市', max_length=60, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, default='0956-', max_length=15, null=True, verbose_name='電話番号')),
                ('bloodtype', models.CharField(blank=True, default='ABOAB', max_length=10, null=True, verbose_name='血液型')),
                ('age', models.IntegerField(blank=True, default='100', null=True, verbose_name='年齢')),
                ('man', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Soen.soenmemberm')),
            ],
            options={
                'verbose_name_plural': 'member詳細',
            },
        ),
        migrations.CreateModel(
            name='healthM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consaltationDay', models.DateField(blank=True, null=True, verbose_name='診察日')),
                ('bloodPressureHigh', models.IntegerField(blank=True, null=True, verbose_name='血圧(高)')),
                ('bloodPressureLow', models.IntegerField(blank=True, null=True, verbose_name='血圧(低)')),
                ('man', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Soen.soenmemberm')),
            ],
            options={
                'verbose_name_plural': '健康診断',
            },
        ),
    ]
