# Generated by Django 4.0.4 on 2022-06-01 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0004_insurancem_alter_genrem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soenmemberdetailm',
            name='man',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberD', to='Soen.soenmemberm'),
        ),
    ]
