# Generated by Django 4.0.4 on 2022-06-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0005_alter_soenmemberdetailm_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancem',
            name='Insurance_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='Insurance_station_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名_整理記号･番号'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='employmentinsurance',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '適用除外'), ('4', '-')], max_length=100, null=True, verbose_name='雇用保険'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='employmentinsurance_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='雇用保険番号'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link1'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link2'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link3'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link4'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='healthInsurance',
            field=models.CharField(blank=True, choices=[('1', '健康保険組合'), ('2', '協会けんぽ（全国健康保険協会）'), ('3', '各種共済組合'), ('4', '国民健康保険'), ('5', '国民健康保険組合（長けん国保）'), ('6', '後期高齢者医療制度'), ('7', '船員保険（全国健康保険協会）'), ('8', '-')], max_length=100, null=True, verbose_name='健康保険'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='man',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberInsurance', to='Soen.soenmemberm'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='pensionInsurance',
            field=models.CharField(blank=True, choices=[('1', '国民年金'), ('2', '厚生年金'), ('3', '-')], max_length=100, null=True, verbose_name='年金保険'),
        ),
        migrations.AddField(
            model_name='insurancem',
            name='retirementCooperation',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='建退協'),
        ),
        migrations.AlterField(
            model_name='healthm',
            name='man',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberHealth', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='specialeducationm',
            name='man',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='soenmemberEducation', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='vehiclem',
            name='man',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberVehicle', to='Soen.soenmemberm'),
        ),
        migrations.CreateModel(
            name='SkillM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('-', '-'), ('有機溶剤作業主任者', '有機溶剤作業主任者'), ('玉掛け技能講習', '玉掛け技能講習'), ('特定化学物質等作業主任者', '特定化学物質等作業主任者'), ('小型移動式クレン運転技能講習', '小型移動式クレン運転技能講習'), ('高所作業車運転技能講習', '高所作業車運転技能講習'), ('技能講習6', '技能講習6'), ('技能講習7', '技能講習7'), ('技能講習8', '技能講習8'), ('技能講習9', '技能講習9'), ('技能講習10', '技能講習10'), ('技能講習11', '技能講習11'), ('技能講習12', '技能講習12'), ('技能講習13', '技能講習13'), ('技能講習14', '技能講習14'), ('技能講習15', '技能講習15'), ('技能講習16', '技能講習16'), ('技能講習17', '技能講習17'), ('技能講習18', '技能講習18'), ('技能講習19', '技能講習19'), ('技能講習20', '技能講習20')], max_length=30, null=True, verbose_name='技能講習')),
                ('man', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='soenmemberSkill', to='Soen.soenmemberm')),
            ],
        ),
        migrations.CreateModel(
            name='LicenceM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('-', '-'), ('1級建築士', '1級建築士'), ('2級建築士', '2級建築士'), ('1級建築施工管理技士', '1級建築施工管理技士'), ('2級建築施工管理技士（建築）', '2級建築施工管理技士（建築）'), ('2級建築施工管理技士（仕上げ）', '2級建築施工管理技士（仕上げ）'), ('1級技能士\u3000内装仕上げ施工（鋼製下地工事作業）', '1級技能士\u3000内装仕上げ施工（鋼製下地工事作業）'), ('2級技能士\u3000内装仕上げ施工（鋼製下地工事作業）', '2級技能士\u3000内装仕上げ施工（鋼製下地工事作業）'), ('1級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）', '1級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）'), ('2級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）', '2級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）'), ('1級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）', '1級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）'), ('2級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）', '2級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）'), ('1級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）', '1級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）'), ('2級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）', '2級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）'), ('1級技能士\u3000表装（表具作業）', '1級技能士\u3000表装（表具作業）'), ('2級技能士\u3000表装（表具作業）', '2級技能士\u3000表装（表具作業）'), ('1級技能士', '1級技能士'), ('2級技能士', '2級技能士'), ('3級技能士', '3級技能士'), ('自動車運転免許', '自動車運転免許'), ('免許20', '免許20')], max_length=40, null=True, verbose_name='免許')),
                ('man', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='soenmemberLicence', to='Soen.soenmemberm')),
            ],
        ),
    ]
