# Generated by Django 4.0.4 on 2022-06-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0006_insurancem_insurance_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencem',
            old_name='name',
            new_name='licence_name',
        ),
        migrations.RenameField(
            model_name='skillm',
            old_name='name',
            new_name='skill_name',
        ),
    ]
