# Generated by Django 4.0.4 on 2022-06-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0007_rename_name_licencem_licence_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancem',
            options={'verbose_name_plural': '社会保険'},
        ),
        migrations.AlterModelOptions(
            name='licencem',
            options={'verbose_name_plural': '免許'},
        ),
        migrations.AlterModelOptions(
            name='skillm',
            options={'verbose_name_plural': '技能講習'},
        ),
        migrations.AlterModelOptions(
            name='soenmemberdetailm',
            options={'verbose_name_plural': 'SoenMember詳細'},
        ),
    ]
