# Generated by Django 4.0.4 on 2022-06-08 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0008_alter_insurancem_options_alter_licencem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soenmemberdetailm',
            name='update',
        ),
        migrations.AlterField(
            model_name='soenmemberm',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3, '3文字以上としてください'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみ入力可')]),
        ),
    ]
