# Generated by Django 4.0.4 on 2022-06-08 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0009_remove_soenmemberdetailm_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthm',
            name='man',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberHealth', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='man',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberInsurance', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='licencem',
            name='man',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='soenmemberLicence', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='skillm',
            name='man',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='soenmemberSkill', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='soenmemberdetailm',
            name='man',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberD', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='specialeducationm',
            name='man',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='soenmemberEducation', to='Soen.soenmemberm'),
        ),
    ]
