# Generated by Django 4.0.4 on 2022-06-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0010_alter_healthm_man_alter_insurancem_man_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclem',
            name='man',
        ),
        migrations.AddField(
            model_name='vehiclem',
            name='man',
            field=models.ManyToManyField(default='', related_name='soenmemberVehicle', to='Soen.soenmemberm'),
        ),
    ]
