# Generated by Django 4.0.4 on 2022-06-09 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0011_remove_vehiclem_man_vehiclem_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soenmemberdetailm',
            name='age',
            field=models.IntegerField(blank=True, default='100', null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみ入力可')], verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='soenmemberm',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, '2文字以上としてください')]),
        ),
    ]
