# Generated by Django 4.0.4 on 2022-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0012_alter_soenmemberdetailm_age_alter_soenmemberm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthm',
            name='bloodPressureHigh',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='血圧(高)'),
        ),
        migrations.AlterField(
            model_name='healthm',
            name='bloodPressureLow',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='血圧(低)'),
        ),
        migrations.AlterField(
            model_name='healthm',
            name='consaltationDay',
            field=models.DateField(blank=True, default='', null=True, verbose_name='診察日'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='Insurance_station',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='保険＿事業所名'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='Insurance_station_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='保険＿事業所名_整理記号･番号'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='employmentinsurance',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '適用除外'), ('4', '-')], default='', max_length=100, null=True, verbose_name='雇用保険'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='employmentinsurance_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='雇用保険番号'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='file1',
            field=models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Link1'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='file2',
            field=models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Link2'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='file3',
            field=models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Link3'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='file4',
            field=models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Link4'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='healthInsurance',
            field=models.CharField(blank=True, choices=[('1', '健康保険組合'), ('2', '協会けんぽ（全国健康保険協会）'), ('3', '各種共済組合'), ('4', '国民健康保険'), ('5', '国民健康保険組合（長けん国保）'), ('6', '後期高齢者医療制度'), ('7', '船員保険（全国健康保険協会）'), ('8', '-')], default='', max_length=100, null=True, verbose_name='健康保険'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='pensionInsurance',
            field=models.CharField(blank=True, choices=[('1', '国民年金'), ('2', '厚生年金'), ('3', '-')], default='', max_length=100, null=True, verbose_name='年金保険'),
        ),
        migrations.AlterField(
            model_name='insurancem',
            name='retirementCooperation',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], default='', max_length=100, null=True, verbose_name='建退協'),
        ),
    ]
