# Generated by Django 4.0.4 on 2022-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0013_alter_healthm_bloodpressurehigh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclem',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='vehiclem',
            name='man',
            field=models.ManyToManyField(to='Soen.soenmemberm'),
        ),
    ]
