# Generated by Django 4.0.4 on 2022-06-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0014_vehiclem_updated_at_alter_vehiclem_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialeducationm',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
