# Generated by Django 4.0.4 on 2022-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0015_specialeducationm_file1'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialeducationm',
            name='image1',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='image/', verbose_name='添付画像', width_field='url_width'),
        ),
    ]
