# Generated by Django 4.0.4 on 2022-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0016_specialeducationm_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialeducationm',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='添付画像'),
        ),
    ]
