# Generated by Django 4.0.4 on 2022-06-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0018_alter_licencem_man_alter_skillm_man_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencem',
            name='man',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberLicence', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='skillm',
            name='man',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberSkill', to='Soen.soenmemberm'),
        ),
        migrations.AlterField(
            model_name='specialeducationm',
            name='man',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soenmemberEducation', to='Soen.soenmemberm'),
        ),
    ]
